# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_tls"
version = "0.9.0"
authors = ["the Deno authors"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"
description = "TLS for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.104.0", path = "../../core" }
lazy_static = "1.4.0"
reqwest = { version = "0.11.4", default-features = false, features = ["rustls-tls", "stream", "gzip", "brotli"] }
rustls = { version = "0.20", features = ["dangerous_configuration"] }
rustls-pemfile = "0.2.1"
rustls-native-certs = "0.5.0"
serde = { version = "1.0.129", features = ["derive"] }
webpki = "0.22"
webpki-roots = "0.22"
